// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: transactions/transactions.proto

package transactions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactorClient is the client API for Transactor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactorClient interface {
	GetTransactions(ctx context.Context, in *TransactionsRequest, opts ...grpc.CallOption) (*TransactionsReply, error)
}

type transactorClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactorClient(cc grpc.ClientConnInterface) TransactorClient {
	return &transactorClient{cc}
}

func (c *transactorClient) GetTransactions(ctx context.Context, in *TransactionsRequest, opts ...grpc.CallOption) (*TransactionsReply, error) {
	out := new(TransactionsReply)
	err := c.cc.Invoke(ctx, "/transactions.Transactor/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactorServer is the server API for Transactor service.
// All implementations must embed UnimplementedTransactorServer
// for forward compatibility
type TransactorServer interface {
	GetTransactions(context.Context, *TransactionsRequest) (*TransactionsReply, error)
	mustEmbedUnimplementedTransactorServer()
}

// UnimplementedTransactorServer must be embedded to have forward compatible implementations.
type UnimplementedTransactorServer struct {
}

func (UnimplementedTransactorServer) GetTransactions(context.Context, *TransactionsRequest) (*TransactionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedTransactorServer) mustEmbedUnimplementedTransactorServer() {}

// UnsafeTransactorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactorServer will
// result in compilation errors.
type UnsafeTransactorServer interface {
	mustEmbedUnimplementedTransactorServer()
}

func RegisterTransactorServer(s grpc.ServiceRegistrar, srv TransactorServer) {
	s.RegisterService(&Transactor_ServiceDesc, srv)
}

func _Transactor_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactorServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transactions.Transactor/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactorServer).GetTransactions(ctx, req.(*TransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transactor_ServiceDesc is the grpc.ServiceDesc for Transactor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transactor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transactions.Transactor",
	HandlerType: (*TransactorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactions",
			Handler:    _Transactor_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions/transactions.proto",
}
